users:
  - user:
      name: '张三'
      openid: 'oO-a2t6Z_awwxOby5Y9eO5VL9Rqg'
      mail: 'aaaa@qq.com'
  - user:
      name: '李四'
      openid: 'oO-a2t7bkGObaacIOd4U1Bpaf1l0'
      mail: 'bbbbb@qq.com'


